import test from 'node:test';
import assert from 'node:assert/strict';
import { execFile, spawn } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { promisify } from 'node:util';
import { createRunRecord, createTaskEnvelope } from '../src/bus/envelopes.mjs';
import { PostgresCoordinationStore } from '../src/coordination/postgres/postgres-coordination-store.mjs';
import { FencedDispatchCoordinator } from '../src/coordination/fenced-dispatch-coordinator.mjs';
import { FencedPolicyCoordinator } from '../src/coordination/fenced-policy-coordinator.mjs';
import { DistributedNativeBoundary, DistributedCancellationBoundary } from '../src/coordination/distributed-native-boundary.mjs';
import { SqlitePersistenceStore } from '../src/persistence/sqlite/sqlite-persistence-store.mjs';
import { AgentBusRepository } from '../src/persistence/repositories/agentbus-repository.mjs';
import { NativeSessionRepository } from '../src/persistence/repositories/native-session-repository.mjs';
import { nativeProfileFingerprint } from '../src/session/native-profile.mjs';

const dsn = process.env.DSH_P3FINAL_POSTGRES_DSN; if (process.env.DSH_P3FINAL_REQUIRE_POSTGRES === '1' && !dsn) throw new Error('real PostgreSQL is required');
const container = process.env.DSH_P3FINAL_CONTAINER_ID; const execFileAsync = promisify(execFile);
test('G8-G10 real PostgreSQL split-brain/native/cancellation integration', { skip: !dsn, timeout: 60_000 }, async (t) => {
  const dir = mkdtempSync(join(tmpdir(), 'dsh-p3final-')); const sqlitePath = join(dir, 'p2.sqlite'); const nativeLedger = join(dir, 'native.ndjson');
  const store = await new PostgresCoordinationStore().open({ connectionString: dsn }); await store.migrate();
  const sqlite = await new SqlitePersistenceStore().open({ path: sqlitePath }); await sqlite.migrate(); const bus = new AgentBusRepository({ store: sqlite });
  t.after(async () => { await sqlite.close(); await store.close(); rmSync(dir, { recursive: true, force: true }); });

  await t.test('G8_CHECKPOINT real coordinator process race and monotonic stale rejection', async () => {
    const barrier = join(dir, 'leader-barrier'); const children = Array.from({ length: 4 }, (_, i) => coordinatorChild(dir, dsn, barrier, `host-${i}`)); writeFileSync(barrier, 'go');
    const results = await Promise.all(children.map(waitJson)); assert.equal(results.filter((x) => x.winner).length, 1); assert.equal(new Set(results.map((x) => x.incarnation)).size, 4);
    const winner = results.find((x) => x.winner); const current = await store.readLeadership('policy'); const staleFence = leaderFence(current); const shortened = await store.renewLeadership(staleFence, 50);
    await waitExpiry(store, shortened); const replacementId = 'coordinator-replacement'; await store.registerCoordinatorIncarnation({ logical_coordinator_id: 'policy', coordinator_incarnation_id: replacementId, host_id: 'host-replacement' }); const next = await store.acquireLeadership({ logical_coordinator_id: 'policy', coordinator_incarnation_id: replacementId, leaseMs: 10_000 });
    assert.equal(next.leader_generation, winner.generation + 1); await assert.rejects(store.fencedPolicyTouch(staleFence), (e) => e.code === 'LEADERSHIP_AUTHORITY_REJECTED'); await store.fencedPolicyTouch(leaderFence(next));
    let durableDecision = { turn: 1, type: 'finish' }; let calls = 0; const policy = new FencedPolicyCoordinator({ coordinationStore: store }); const reconstructed = await policy.decideAndCommit({ leaderFence: leaderFence(next), readCommitted: () => durableDecision, decide: async () => { calls += 1; }, commitDecision: (d) => { durableDecision = d; return d; } }); assert.equal(reconstructed.driverCalled, false); assert.equal(calls, 0);
  });

  await t.test('G9_CHECKPOINT fenced RESUME_STARTED and cancellation truth', async () => {
    const workerA = 'native-worker-a', workerB = 'native-worker-b'; for (const id of [workerA, workerB]) await store.registerWorkerIncarnation(worker(id));
    const ids = { task_id: 'native-task', run_id: 'native-run', dispatch_attempt_id: 'native-attempt' }; const work = await store.registerWorkIdentity({ work_item_id: 'native-work', work_kind: 'TASK_DISPATCH', ...ids }); const claim = await store.acquireClaim({ work_item_id: work.work_item_id, worker_incarnation_id: workerA, leaseMs: 5_000 }); const fence = claimFence(claim);
    const dispatch = new FencedDispatchCoordinator({ coordinationStore: store, agentBusRepository: bus }); await dispatch.prepareIntent({ fence, lineage: ids, task: createTaskEnvelope({ id: ids.task_id, recipient: 'alpha', body: 'redacted-proof-task' }), run: createRunRecord({ id: ids.run_id, taskId: ids.task_id, agent: 'alpha' }), backend: 'alpha' }); await dispatch.markDispatchStarted({ fence, lineage: ids }); await dispatch.recordRemoteStarted({ fence, lineage: ids, evidence: { backend: 'alpha', nativeSessionId: 'session-proof', product: 'cli', version: '1' } });
    const nativeRepo = new NativeSessionRepository({ store: sqlite, knownBackends: ['alpha'] }); const profileBase = { backend: 'alpha', product: 'cli', version: '1', transport: 'stdio', capabilities: { resume_existing: 'PROVED', interrupt_active_turn: 'PROVED' } }; const fp = nativeProfileFingerprint(profileBase); nativeRepo.capture({ id: 'native-record', backend: 'alpha', nativeSessionId: 'session-proof', nativeReference: { nativeSessionId: 'session-proof' }, product: 'cli', version: '1', transport: 'stdio', capabilityFingerprint: fp, taskId: ids.task_id, runId: ids.run_id, dispatchAttemptId: ids.dispatch_attempt_id, capturedAt: new Date().toISOString() });
    let resumeCalls = 0; const profile = { ...profileBase, bridge: { resume: async () => { resumeCalls += 1; appendLedger(nativeLedger, 'resume'); return { status: 'resumed', usable: true }; } } }; const native = new DistributedNativeBoundary({ coordinationStore: store, repository: nativeRepo, profileResolver: () => profile }); const recovery = { classification: 'NATIVE_RECONCILE_REQUIRED' };
    assert.equal((await native.reconcile({ fence, lineage: ids, recovery })).status, 'RECONCILED'); assert.equal(resumeCalls, 1); assert.equal((await native.reconcile({ fence, lineage: ids, recovery })).status, 'RECONCILED'); assert.equal(resumeCalls, 1);
    const leader = await store.readLeadership('policy'); const cancellation = new DistributedCancellationBoundary({ coordinationStore: store }); await cancellation.request({ leaderFence: leaderFence(leader), workItemId: work.work_item_id }); let interrupts = 0; const cancelled = await cancellation.interrupt({ fence, capability: 'PROVED', interrupt: async () => { interrupts += 1; appendLedger(nativeLedger, 'interrupt'); return { status: 'cancelled', observed: true }; } }); assert.equal(cancelled.status, 'CANCELLED'); assert.equal(interrupts, 1);

    const startedIds = { task_id: 'started-task', run_id: 'started-run', dispatch_attempt_id: 'started-attempt' }; const startedWork = await store.registerWorkIdentity({ work_item_id: 'started-work', work_kind: 'TASK_DISPATCH', ...startedIds }); const startedClaim = await store.acquireClaim({ work_item_id: startedWork.work_item_id, worker_incarnation_id: workerA, leaseMs: 5_000 });
    nativeRepo.capture({ id: 'started-record', backend: 'alpha', nativeSessionId: 'started-session', nativeReference: { nativeSessionId: 'started-session' }, product: 'cli', version: '1', transport: 'stdio', capabilityFingerprint: fp, taskId: startedIds.task_id, runId: startedIds.run_id, dispatchAttemptId: startedIds.dispatch_attempt_id, capturedAt: new Date().toISOString() }); nativeRepo.startReconcile('started-record', new Date().toISOString());
    assert.equal((await native.reconcile({ fence: claimFence(startedClaim), lineage: startedIds, recovery })).status, 'OPERATOR_ACTION_REQUIRED'); assert.equal(resumeCalls, 1);

    const mismatchIds = { task_id: 'mismatch-task', run_id: 'mismatch-run', dispatch_attempt_id: 'mismatch-attempt' }; const mismatchWork = await store.registerWorkIdentity({ work_item_id: 'mismatch-work', work_kind: 'TASK_DISPATCH', ...mismatchIds }); const mismatchClaim = await store.acquireClaim({ work_item_id: mismatchWork.work_item_id, worker_incarnation_id: workerA, leaseMs: 5_000 }); nativeRepo.capture({ id: 'mismatch-record', backend: 'alpha', nativeSessionId: 'mismatch-session', nativeReference: { nativeSessionId: 'mismatch-session' }, product: 'cli', version: '1', transport: 'stdio', capabilityFingerprint: fp, taskId: mismatchIds.task_id, runId: mismatchIds.run_id, dispatchAttemptId: mismatchIds.dispatch_attempt_id, capturedAt: new Date().toISOString() }); const mismatchNative = new DistributedNativeBoundary({ coordinationStore: store, repository: nativeRepo, profileResolver: () => ({ ...profile, version: '2' }) }); assert.equal((await mismatchNative.reconcile({ fence: claimFence(mismatchClaim), lineage: mismatchIds, recovery })).status, 'PROFILE_MISMATCH'); assert.equal(resumeCalls, 1);

    const staleIds = { task_id: 'stale-task', run_id: 'stale-run', dispatch_attempt_id: 'stale-attempt' }; const staleWork = await store.registerWorkIdentity({ work_item_id: 'stale-work', work_kind: 'TASK_DISPATCH', ...staleIds }); const staleClaim = await store.acquireClaim({ work_item_id: staleWork.work_item_id, worker_incarnation_id: workerA, leaseMs: 5_000 }); nativeRepo.capture({ id: 'stale-record', backend: 'alpha', nativeSessionId: 'stale-session', nativeReference: { nativeSessionId: 'stale-session' }, product: 'cli', version: '1', transport: 'stdio', capabilityFingerprint: fp, taskId: staleIds.task_id, runId: staleIds.run_id, dispatchAttemptId: staleIds.dispatch_attempt_id, capturedAt: new Date().toISOString() }); await store.releaseClaim(claimFence(staleClaim)); await store.acquireClaim({ work_item_id: staleWork.work_item_id, worker_incarnation_id: workerB, leaseMs: 5_000 }); await assert.rejects(native.reconcile({ fence: claimFence(staleClaim), lineage: staleIds, recovery }), (e) => e.code === 'CLAIM_AUTHORITY_REJECTED'); assert.equal(resumeCalls, 1);

    const cancelIds = { task_id: 'cancel-task', run_id: 'cancel-run', dispatch_attempt_id: 'cancel-attempt' }; const cancelWork = await store.registerWorkIdentity({ work_item_id: 'cancel-work', work_kind: 'TASK_DISPATCH', ...cancelIds }); const cancelClaim = await store.acquireClaim({ work_item_id: cancelWork.work_item_id, worker_incarnation_id: workerA, leaseMs: 5_000 }); await cancellation.request({ leaderFence: leaderFence(leader), workItemId: cancelWork.work_item_id }); const unsupported = await cancellation.interrupt({ fence: claimFence(cancelClaim), capability: 'UNPROVEN', interrupt: async () => { interrupts += 1; } }); assert.equal(unsupported.status, 'UNSUPPORTED'); assert.equal(interrupts, 1);

    const lateIds = { task_id: 'late-task', run_id: 'late-run', dispatch_attempt_id: 'late-attempt' }; const lateWork = await store.registerWorkIdentity({ work_item_id: 'late-work', work_kind: 'TASK_DISPATCH', ...lateIds }); const lateClaim = await store.acquireClaim({ work_item_id: lateWork.work_item_id, worker_incarnation_id: workerA, leaseMs: 5_000 }); await cancellation.request({ leaderFence: leaderFence(leader), workItemId: lateWork.work_item_id }); let releaseInterrupt; const pendingInterrupt = cancellation.interrupt({ fence: claimFence(lateClaim), capability: 'PROVED', interrupt: () => new Promise((resolve) => { releaseInterrupt = () => resolve({ status: 'cancelled', observed: true }); }) }); while (!releaseInterrupt) await new Promise((r) => setTimeout(r, 1)); await store.releaseClaim(claimFence(lateClaim)); await store.acquireClaim({ work_item_id: lateWork.work_item_id, worker_incarnation_id: workerB, leaseMs: 5_000 }); releaseInterrupt(); assert.equal((await pendingInterrupt).status, 'STALE_INTERRUPT_RESULT_REJECTED'); assert.equal((await store.readCancellation(lateWork.work_item_id)).state, 'INTERRUPT_STARTED');
  });

  await t.test('G10_CHECKPOINT A-Z matrix preserves local fencing while acknowledging external effects', async () => {
    const rows = ledgerRows(nativeLedger); assert.equal(rows.filter((x) => x === 'resume').length, 1); assert.equal(rows.filter((x) => x === 'interrupt').length, 1); assert.equal(await store.readSchemaVersion(), 4); assert.equal(await sqlite.readSchemaVersion(), 6);
    console.log('P3 FINAL A-Z: PASS; real coordinator processes=4; tokens/DSN/task bodies redacted; no provider exactly-once claim');
  });
  await t.test('G10 coordinator PostgreSQL outage freezes policy authority', async () => {
    assert.ok(container); const leader = await store.readLeadership('policy'); await execFileAsync('docker', ['stop', '--time', '0', container], { windowsHide: true }); await assert.rejects(store.fencedPolicyTouch(leaderFence(leader))); assert.equal(ledgerRows(nativeLedger).length, 2);
  });
});
function worker(id) { return { logical_worker_id: id, worker_incarnation_id: id, host_id: `host-${id}`, installed_profiles: [], capacity: { max_concurrency: 1, reported_in_use: 0 } }; }
function claimFence(c) { return { work_item_id: c.work_item_id, owner_worker_incarnation_id: c.owner_worker_incarnation_id, fencing_generation: c.fencing_generation, fencing_token: c.fencing_token }; }
function leaderFence(c) { return { logical_coordinator_id: c.logical_coordinator_id, owner_coordinator_incarnation_id: c.owner_coordinator_incarnation_id, leader_generation: c.leader_generation, leadership_token: c.leadership_token }; }
function coordinatorChild(dir, postgresDsn, barrier, hostId) { const config = join(dir, `coord-${hostId}.json`); writeFileSync(config, JSON.stringify({ logicalId: 'policy', hostId, barrier, leaseMs: 5_000 })); return spawn(process.execPath, ['scripts/fixtures/p3-final-coordinator.mjs', config], { cwd: process.cwd(), env: { ...process.env, DSH_P3FINAL_POSTGRES_DSN: postgresDsn }, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] }); }
function waitJson(child) { return new Promise((resolve, reject) => { let out = '', err = ''; child.stdout.on('data', (x) => { out += x; }); child.stderr.on('data', (x) => { err += x; }); child.on('exit', (code) => code === 0 ? resolve(JSON.parse(out.trim())) : reject(new Error(err))); }); }
async function waitExpiry(s, leadership) { while (Date.parse(await s.serverNow()) <= Date.parse(leadership.expires_at)) await new Promise((r) => setTimeout(r, 5)); }
function appendLedger(path, event) { writeFileSync(path, `${JSON.stringify({ event })}\n`, { flag: 'a', flush: true }); }
function ledgerRows(path) { return existsSync(path) ? readFileSync(path, 'utf8').trim().split('\n').filter(Boolean).map((x) => JSON.parse(x).event) : []; }
