const {app,BrowserWindow}=require('electron');const Database=require('better-sqlite3');const {spawn}=require('node:child_process');const path=require('node:path');const fs=require('node:fs');
let child,window;const emit=(event,data={})=>process.stdout.write(`${JSON.stringify({event,...data})}\n`);
if(!app.requestSingleInstanceLock()){emit('p0a.second-instance-refused');app.quit();}else{
 app.on('window-all-closed',()=>{});
 app.on('second-instance',()=>{emit('p0a.second-instance-observed');window?.show();});
 app.whenReady().then(async()=>{const db=new Database(':memory:');db.exec('CREATE TABLE proof(value TEXT); INSERT INTO proof VALUES (\'electron-native-ok\')');const nativeValue=db.prepare('SELECT value FROM proof').pluck().get();emit('p0a.better-sqlite3',{value:nativeValue,electron:process.versions.electron});db.close();if(process.env.P6_P0_PROOF_FILE)fs.writeFileSync(process.env.P6_P0_PROOF_FILE,JSON.stringify({nativeValue,electron:process.versions.electron,pid:process.pid}));
  window=new BrowserWindow({show:false,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});await window.loadFile(path.join(__dirname,'renderer.html'));emit('p0a.window-ready');
  const command=process.env.P6_P0_CHILD_COMMAND;if(command){const args=JSON.parse(process.env.P6_P0_CHILD_ARGS||'[]');child=spawn(command,args,{cwd:process.env.P6_P0_CHILD_CWD||process.cwd(),env:process.env,stdio:['ignore','pipe','pipe'],windowsHide:true,shell:false});emit('p0a.child-started',{pid:child.pid});child.stdout.setEncoding('utf8');child.stderr.setEncoding('utf8');let exercised=false;child.stdout.on('data',v=>{process.stdout.write(v);if(!exercised&&(v.includes('runtime.ready')||v.includes('p5.runtime.started'))){exercised=true;emit('p0a.readiness-observed');window.webContents.once('render-process-gone',()=>{emit('p0a.renderer-crash-child-alive',{alive:child.exitCode===null});window.destroy();emit('p0a.window-closed-child-alive',{alive:child.exitCode===null});setTimeout(requestStop,Number(process.env.P6_P0_STOP_DELAY_MS||150));});window.webContents.forcefullyCrashRenderer();}});child.stderr.on('data',v=>emit('p0a.child-stderr',{text:String(v).replace(/(?:postgres(?:ql)?|https?):\/\/\S+/gi,'[REDACTED_URL]').slice(0,1000)}));child.on('exit',code=>{emit('p0a.child-exit',{code});setTimeout(()=>app.quit(),50);});}
  else{emit('p0a.packaged-smoke-pass');app.quit();}
 });
 app.on('before-quit',()=>{if(process.env.P6_P0_KEEP_CHILD!=='1'&&child?.exitCode===null)child.kill();});
}
function requestStop(){const pipe=process.env.P6_P0_CONTROL_PIPE;if(pipe){const net=require('node:net'),socket=net.createConnection(pipe);socket.once('connect',()=>socket.end(`${JSON.stringify({id:'electron-stop',operation:'SHUTDOWN'})}\n`));socket.once('error',error=>emit('p0a.inband-stop-error',{code:error.code}));emit('p0a.inband-stop-requested');}else{const ok=child?.kill('SIGTERM');emit('p0a.signal-stop-requested',{ok});}}
